package tiny.mybatis2.mbg.model;

import java.io.Serializable;

public class UserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.uid
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.mobile
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.password
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.password_salt
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private String passwordSalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.unick
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private String unick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.uface
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private String uface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.realname
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.sex
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.birth
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private String birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.province_id
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Integer provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.city_id
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.area_id
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.address
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.education
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Byte education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.job
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Byte job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.company
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.channel_id
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Integer channelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.status
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.point_1
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Integer point1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.add_ip
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private String addIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.add_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Integer addUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.add_time
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.update_time
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Integer updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.update_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Integer updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g2_user.mark
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private Boolean mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.uid
     *
     * @return the value of g2_user.uid
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.uid
     *
     * @param uid the value for g2_user.uid
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.mobile
     *
     * @return the value of g2_user.mobile
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.mobile
     *
     * @param mobile the value for g2_user.mobile
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.password
     *
     * @return the value of g2_user.password
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.password
     *
     * @param password the value for g2_user.password
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.password_salt
     *
     * @return the value of g2_user.password_salt
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public String getPasswordSalt() {
        return passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.password_salt
     *
     * @param passwordSalt the value for g2_user.password_salt
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt == null ? null : passwordSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.unick
     *
     * @return the value of g2_user.unick
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public String getUnick() {
        return unick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.unick
     *
     * @param unick the value for g2_user.unick
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setUnick(String unick) {
        this.unick = unick == null ? null : unick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.uface
     *
     * @return the value of g2_user.uface
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public String getUface() {
        return uface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.uface
     *
     * @param uface the value for g2_user.uface
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setUface(String uface) {
        this.uface = uface == null ? null : uface.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.realname
     *
     * @return the value of g2_user.realname
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.realname
     *
     * @param realname the value for g2_user.realname
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.sex
     *
     * @return the value of g2_user.sex
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.sex
     *
     * @param sex the value for g2_user.sex
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.birth
     *
     * @return the value of g2_user.birth
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.birth
     *
     * @param birth the value for g2_user.birth
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.province_id
     *
     * @return the value of g2_user.province_id
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.province_id
     *
     * @param provinceId the value for g2_user.province_id
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.city_id
     *
     * @return the value of g2_user.city_id
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.city_id
     *
     * @param cityId the value for g2_user.city_id
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.area_id
     *
     * @return the value of g2_user.area_id
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.area_id
     *
     * @param areaId the value for g2_user.area_id
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.address
     *
     * @return the value of g2_user.address
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.address
     *
     * @param address the value for g2_user.address
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.education
     *
     * @return the value of g2_user.education
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Byte getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.education
     *
     * @param education the value for g2_user.education
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setEducation(Byte education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.job
     *
     * @return the value of g2_user.job
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Byte getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.job
     *
     * @param job the value for g2_user.job
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setJob(Byte job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.company
     *
     * @return the value of g2_user.company
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.company
     *
     * @param company the value for g2_user.company
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.channel_id
     *
     * @return the value of g2_user.channel_id
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.channel_id
     *
     * @param channelId the value for g2_user.channel_id
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.status
     *
     * @return the value of g2_user.status
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.status
     *
     * @param status the value for g2_user.status
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.point_1
     *
     * @return the value of g2_user.point_1
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Integer getPoint1() {
        return point1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.point_1
     *
     * @param point1 the value for g2_user.point_1
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setPoint1(Integer point1) {
        this.point1 = point1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.add_ip
     *
     * @return the value of g2_user.add_ip
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public String getAddIp() {
        return addIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.add_ip
     *
     * @param addIp the value for g2_user.add_ip
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setAddIp(String addIp) {
        this.addIp = addIp == null ? null : addIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.add_user
     *
     * @return the value of g2_user.add_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Integer getAddUser() {
        return addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.add_user
     *
     * @param addUser the value for g2_user.add_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setAddUser(Integer addUser) {
        this.addUser = addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.add_time
     *
     * @return the value of g2_user.add_time
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.add_time
     *
     * @param addTime the value for g2_user.add_time
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.update_time
     *
     * @return the value of g2_user.update_time
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.update_time
     *
     * @param updateTime the value for g2_user.update_time
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.update_user
     *
     * @return the value of g2_user.update_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.update_user
     *
     * @param updateUser the value for g2_user.update_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g2_user.mark
     *
     * @return the value of g2_user.mark
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public Boolean getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g2_user.mark
     *
     * @param mark the value for g2_user.mark
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    public void setMark(Boolean mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", mobile=").append(mobile);
        sb.append(", password=").append(password);
        sb.append(", passwordSalt=").append(passwordSalt);
        sb.append(", unick=").append(unick);
        sb.append(", uface=").append(uface);
        sb.append(", realname=").append(realname);
        sb.append(", sex=").append(sex);
        sb.append(", birth=").append(birth);
        sb.append(", provinceId=").append(provinceId);
        sb.append(", cityId=").append(cityId);
        sb.append(", areaId=").append(areaId);
        sb.append(", address=").append(address);
        sb.append(", education=").append(education);
        sb.append(", job=").append(job);
        sb.append(", company=").append(company);
        sb.append(", channelId=").append(channelId);
        sb.append(", status=").append(status);
        sb.append(", point1=").append(point1);
        sb.append(", addIp=").append(addIp);
        sb.append(", addUser=").append(addUser);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", mark=").append(mark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}