package tiny.mybatis2.mbg.xml;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tiny.mybatis2.mbg.model.UserInfo;
import tiny.mybatis2.mbg.model.UserInfoExample;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    long countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    int insert(UserInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    int insertSelective(UserInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    UserInfo selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    int updateByExampleSelective(@Param("row") UserInfo row, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    int updateByExample(@Param("row") UserInfo row, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    int updateByPrimaryKeySelective(UserInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g2_user
     *
     * @mbg.generated Fri Nov 04 10:15:48 CST 2022
     */
    int updateByPrimaryKey(UserInfo row);
}